adminUser:
  password: local:manzarek/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkinsx@beyondit.it
  token: local:manzarek/pipelineUser:token
  username: JenkinsxBeyondIt
prow:
  hmacToken: local:manzarek/prow:hmacToken
